In [1]:
import torch
torch.__version__

'2.1.2+cpu'

## Intro to Tensors



Tensors are datatypes to represent numbers in PyTorch or any Deep Learning Framework for that matter

In [2]:
scalar = torch.tensor(2)
scalar

tensor(2)

In [3]:
scalar.item() # Will return the value 7

2

In [4]:
scalar.ndim  # Returns the number of dimensions

0

### A tensor is of the following types:

1. Scalar (1 dimension or ndim=0)
2. Vector (2 dimensional or ndim=1)
3. Matrix (3 dimensional or ndim=2)
4. Tensor (n dimensional where n could be anything from 0 to inf)

Tensor could be of any datatypes:
* float32
* float64
* float16
* float128, etc

In [5]:
vector = torch.tensor([4,65,2,4],dtype=torch.float32)
vector.ndim

1

In [6]:
vector.dtype

torch.float32

In [7]:
matrix = torch.tensor([[1,2,3],[4,5,6],[7,8,9]],dtype=torch.float64)

In [8]:
matrix.ndim

2

In [9]:
matrix.shape

torch.Size([3, 3])

In [10]:
matrix

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]], dtype=torch.float64)

In [79]:
tensors = torch.tensor(
    [
        [
            [2,3,4],
            [1,2,3],
            [6,80,35]
        ],
        [
            [5,7,34],
            [3456,736,234536],
            [13456134,13461346e-12,123452346e+12]
        ],
        [
            [34561345e-34,24563e+134,2356121345e-123],
            [345234,234623456,35678345678],
            [2346346267,5683567845e-346,34627]
        ]
    
    ],
    dtype=torch.float64
    )

In [80]:
tensors.dtype

torch.float64

In [13]:
tensors.shape

torch.Size([3, 3, 3])

In [14]:
tensors.reshape(3,9)
# Used to reshape the shape of the tensor

tensor([[ 2.0000e+00,  3.0000e+00,  4.0000e+00,  1.0000e+00,  2.0000e+00,
          3.0000e+00,  6.0000e+00,  8.0000e+01,  3.5000e+01],
        [ 5.0000e+00,  7.0000e+00,  3.4000e+01,  3.4560e+03,  7.3600e+02,
          2.3454e+05,  1.3456e+07,  1.3461e-05,  1.2345e+20],
        [ 3.4561e-27, 2.4563e+138, 2.3561e-114,  3.4523e+05,  2.3462e+08,
          3.5678e+10,  2.3463e+09,  0.0000e+00,  3.4627e+04]],
       dtype=torch.float64)

In [15]:
# Creating tensors with serial/range values


range_tensor = torch.arange(1,1000,2,dtype=torch.float64)

In [16]:
range_tensor.shape,range_tensor.ndim

(torch.Size([500]), 1)

In [17]:
range_tensor.reshape(5,4,5,5)

tensor([[[[  1.,   3.,   5.,   7.,   9.],
          [ 11.,  13.,  15.,  17.,  19.],
          [ 21.,  23.,  25.,  27.,  29.],
          [ 31.,  33.,  35.,  37.,  39.],
          [ 41.,  43.,  45.,  47.,  49.]],

         [[ 51.,  53.,  55.,  57.,  59.],
          [ 61.,  63.,  65.,  67.,  69.],
          [ 71.,  73.,  75.,  77.,  79.],
          [ 81.,  83.,  85.,  87.,  89.],
          [ 91.,  93.,  95.,  97.,  99.]],

         [[101., 103., 105., 107., 109.],
          [111., 113., 115., 117., 119.],
          [121., 123., 125., 127., 129.],
          [131., 133., 135., 137., 139.],
          [141., 143., 145., 147., 149.]],

         [[151., 153., 155., 157., 159.],
          [161., 163., 165., 167., 169.],
          [171., 173., 175., 177., 179.],
          [181., 183., 185., 187., 189.],
          [191., 193., 195., 197., 199.]]],


        [[[201., 203., 205., 207., 209.],
          [211., 213., 215., 217., 219.],
          [221., 223., 225., 227., 229.],
          [231., 233., 2

In [18]:
range_tensor.reshape(5,5,2,10)

tensor([[[[  1.,   3.,   5.,   7.,   9.,  11.,  13.,  15.,  17.,  19.],
          [ 21.,  23.,  25.,  27.,  29.,  31.,  33.,  35.,  37.,  39.]],

         [[ 41.,  43.,  45.,  47.,  49.,  51.,  53.,  55.,  57.,  59.],
          [ 61.,  63.,  65.,  67.,  69.,  71.,  73.,  75.,  77.,  79.]],

         [[ 81.,  83.,  85.,  87.,  89.,  91.,  93.,  95.,  97.,  99.],
          [101., 103., 105., 107., 109., 111., 113., 115., 117., 119.]],

         [[121., 123., 125., 127., 129., 131., 133., 135., 137., 139.],
          [141., 143., 145., 147., 149., 151., 153., 155., 157., 159.]],

         [[161., 163., 165., 167., 169., 171., 173., 175., 177., 179.],
          [181., 183., 185., 187., 189., 191., 193., 195., 197., 199.]]],


        [[[201., 203., 205., 207., 209., 211., 213., 215., 217., 219.],
          [221., 223., 225., 227., 229., 231., 233., 235., 237., 239.]],

         [[241., 243., 245., 247., 249., 251., 253., 255., 257., 259.],
          [261., 263., 265., 267., 269., 271., 273

In [19]:
# Creaing random tensors

random_tensor = torch.rand(size=(8,10),dtype=torch.float32)
random_tensor.shape

torch.Size([8, 10])

In [20]:
random_tensor.ndim

2

In [21]:
random_tensor.reshape(5,2,2,4)

tensor([[[[0.8915, 0.9348, 0.3997, 0.1713],
          [0.6523, 0.0638, 0.0519, 0.1029]],

         [[0.9113, 0.6324, 0.4451, 0.0576],
          [0.6129, 0.5743, 0.3666, 0.0042]]],


        [[[0.7721, 0.5056, 0.0961, 0.8430],
          [0.4996, 0.4087, 0.8512, 0.6697]],

         [[0.1951, 0.6874, 0.6946, 0.2205],
          [0.8299, 0.2834, 0.6622, 0.1738]]],


        [[[0.4516, 0.0903, 0.2865, 0.0048],
          [0.1778, 0.2133, 0.0543, 0.3170]],

         [[0.0640, 0.1719, 0.0668, 0.5432],
          [0.9459, 0.4666, 0.6437, 0.5169]]],


        [[[0.5014, 0.9058, 0.9165, 0.0843],
          [0.3577, 0.6969, 0.1168, 0.5029]],

         [[0.7722, 0.3672, 0.2239, 0.7751],
          [0.4048, 0.6617, 0.6331, 0.3944]]],


        [[[0.9371, 0.5785, 0.4253, 0.6874],
          [0.3985, 0.9738, 0.0064, 0.7368]],

         [[0.9645, 0.3292, 0.1642, 0.3541],
          [0.2737, 0.1858, 0.0079, 0.8864]]]])

In [22]:
random_tensor = torch.rand(size=(8,10,10))

random_tensor.shape

torch.Size([8, 10, 10])

In [23]:
random_tensor.reshape(1,-1).shape

torch.Size([1, 800])

In [24]:
random_tensor.reshape(10,10,8).reshape(1,-1).shape, random_tensor.reshape(10,10,8).reshape(1,-1).shape



(torch.Size([1, 800]), torch.Size([1, 800]))

In [25]:
random_tensor.reshape(100,1,8)

tensor([[[8.8592e-01, 9.1505e-01, 7.1631e-01, 1.6403e-01, 7.5505e-01,
          2.1693e-02, 5.3712e-01, 9.8310e-03]],

        [[4.7302e-01, 4.5652e-01, 2.7715e-01, 5.0594e-01, 3.0015e-01,
          4.8413e-01, 3.1122e-01, 7.2467e-01]],

        [[4.2400e-01, 1.7855e-01, 1.2529e-01, 5.4623e-01, 1.0514e-01,
          6.4981e-01, 4.0180e-01, 7.6912e-02]],

        [[9.1401e-01, 1.9408e-01, 3.0086e-01, 3.8035e-01, 6.1968e-01,
          2.4241e-01, 1.4284e-02, 8.7622e-01]],

        [[9.2792e-01, 6.5639e-01, 4.3621e-01, 9.0612e-01, 8.3480e-02,
          1.4978e-01, 4.8439e-02, 8.5617e-01]],

        [[5.4563e-01, 2.8147e-01, 3.2414e-01, 7.2571e-01, 2.0595e-01,
          4.1651e-01, 8.6920e-01, 6.7001e-01]],

        [[8.3364e-01, 5.5342e-01, 3.5506e-01, 6.1908e-01, 8.1142e-01,
          4.5062e-01, 2.4133e-01, 2.6830e-01]],

        [[8.0883e-01, 8.4319e-01, 6.7217e-01, 3.5576e-01, 9.0577e-01,
          7.3804e-03, 2.5669e-01, 9.7339e-01]],

        [[7.9376e-01, 7.4975e-01, 6.0681e-01, 3.

In [26]:
# Creating Special tensors like zeroes and ones from pre built functions
ones = torch.ones(size=(224,224,3),dtype=torch.float64)
zeros = torch.zeros(size=(224,224,3),dtype=torch.float64)

In [27]:
ones

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         ...,
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         ...,
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         ...,
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        ...,

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         ...,
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         ...,
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         ...,
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]], dtype=torch.float64)

In [28]:
zeros

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        ...,

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]], dtype=torch.float64)

In [29]:
zeros_like = torch.zeros_like(random_tensor)
zeros_like.shape

torch.Size([8, 10, 10])

In [30]:
ones_like = torch.ones_like(range_tensor)
ones_like.shape

torch.Size([500])

In [31]:
# Creating tensors from another tensor and changing the dtype

float_32_tensor = torch.rand(size=(1,10),dtype=torch.float32)
float_16_tensor = float_32_tensor.type(torch.float16)

In [32]:
float_16_tensor * float_32_tensor

tensor([[0.1118, 0.1998, 0.4417, 0.1874, 0.1477, 0.0508, 0.2021, 0.0060, 0.1288,
         0.0020]])

In [33]:
int_32_tensor = torch.arange(0,10,dtype=torch.int32)
int_32_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [34]:
float_16_tensor * int_32_tensor

tensor([[0.0000, 0.4470, 1.3291, 1.2988, 1.5371, 1.1270, 2.6973, 0.5439, 2.8711,
         0.4053]], dtype=torch.float16)

# Getting Information from the tensors


### General errors in tensor operations

1. Datatype of the tensor: tensor.dtype
2. Device of the tensor: tensor.device
3. Shape of the tensor: tensor.shape

In [35]:
some_tensor = torch.rand(size=(10,10))
print(f"Datatype: {some_tensor.dtype}")
print(f"Device: {some_tensor.device}")
print(f"Shape: {some_tensor.shape}")

Datatype: torch.float32
Device: cpu
Shape: torch.Size([10, 10])


# Manipulating tensors (Tensor Operations)

Tensor operations include: 
1. Addition
2. Subtraction
3. Multiplication (element-wise)
4. Division 
5. Matrix Multiplication

To train a neural network torch combines one or more of these functions to train the network

In [36]:
tensor = torch.tensor([10,100,1000])
tensor, tensor + 1

(tensor([  10,  100, 1000]), tensor([  11,  101, 1001]))

In [37]:
tensor, tensor - 1

(tensor([  10,  100, 1000]), tensor([  9,  99, 999]))

In [38]:
tensor, tensor * 10

(tensor([  10,  100, 1000]), tensor([  100,  1000, 10000]))

In [39]:
tensor, tensor / 10

(tensor([  10,  100, 1000]), tensor([  1.,  10., 100.]))

In [40]:
# PyTorch inbuilt functions

torch.add(tensor,100)

tensor([ 110,  200, 1100])

In [41]:
torch.subtract(tensor,100)

tensor([-90,   0, 900])

In [42]:
torch.multiply(tensor,100)

tensor([  1000,  10000, 100000])

In [43]:
torch.mul(tensor,100)

tensor([  1000,  10000, 100000])

In [44]:
torch.divide(tensor,10)

tensor([  1.,  10., 100.])

In [45]:
torch.div(tensor,10)

tensor([  1.,  10., 100.])

### Matrix Multiplication

In [46]:
# Element wise multiplication
tensor * tensor

tensor([    100,   10000, 1000000])

In [47]:
# Matrix Multiplication
simpletensor = torch.tensor([1,2,3])
torch.matmul(simpletensor,simpletensor)
# 1*1 + 2*2 + 3*3 = 14

tensor(14)

In [55]:
random_huge_tensor = torch.rand(size=(1,1000000000),dtype=torch.float64)
random_huge_tensor.shape

torch.Size([1, 1000000000])

In [56]:
%%time
torch.matmul(random_huge_tensor,random_huge_tensor.reshape(-1,1))

CPU times: user 1.33 s, sys: 0 ns, total: 1.33 s
Wall time: 1.33 s


tensor([[3.3333e+08]], dtype=torch.float64)

In [74]:
torch.matmul(tensor,tensor.T)

tensor(1010100)

# Tensor Aggregation

1. Min
2. Max
3. Mean
4. Sum
5. Aggregation

In [86]:
# Finding the min
tensors.min() , torch.min(tensors), tensors.amin(), torch.amin(tensors)

(tensor(0., dtype=torch.float64),
 tensor(0., dtype=torch.float64),
 tensor(0., dtype=torch.float64),
 tensor(0., dtype=torch.float64))

In [87]:
# Finding the max
tensors.max() , torch.max(tensors), tensors.amax() , torch.amax(tensors)

(tensor(2.4563e+138, dtype=torch.float64),
 tensor(2.4563e+138, dtype=torch.float64),
 tensor(2.4563e+138, dtype=torch.float64),
 tensor(2.4563e+138, dtype=torch.float64))

In [88]:
# Finding the sum
torch.sum(tensors), tensors.sum()

(tensor(2.4563e+138, dtype=torch.float64),
 tensor(2.4563e+138, dtype=torch.float64))

In [89]:
tensors.mean(), torch.mean(tensors)

(tensor(9.0974e+136, dtype=torch.float64),
 tensor(9.0974e+136, dtype=torch.float64))

In [92]:
# Finding the index position of the minimum value of that tensor
tensors.argmin()

tensor(25)

In [98]:
# Finding the index position of the maximum value of that tensor
tensors.argmax()

tensor(19)

## Reshaping, Stacking, Squeezing and Unsqueezing tensors

* Reshaping: Change the shape of the tensor ```(.reshape() method)```
* Stacking: Putting tensors on top of each other `vertical stacking(vstack)` or besides each other `hoziontal stacking (hstack)`.
* Squeezing: Reduce the dimension of the tensor by `1`
* Unsqueezing: Increase the dimension of the tensor by `1`
* Permute: Return a view of a input with dimensions permuted (swapped) in a certain way.

In [120]:
# Lets create a tensor
x = torch.arange(0,10)
x.shape

torch.Size([10])

In [122]:
# Reshaping the tensor
x.reshape(2,1,5), x.reshape(2,1,5).shape

(tensor([[[0, 1, 2, 3, 4]],
 
         [[5, 6, 7, 8, 9]]]),
 torch.Size([2, 1, 5]))

In [123]:
x.reshape(-1,1), x.reshape(-1,1).shape

(tensor([[0],
         [1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([10, 1]))

In [117]:
x.reshape(1,-1), x.reshape(1,-1).shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [124]:
x.reshape(5,2)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

#### View

It returns a different view of the original tensor but from the same memory location.

In [126]:
z = x.view(2,5)
z

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [127]:
# Changing z will change x
z[:,0] = 5
x

tensor([5, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Stacking Tensors

In [137]:
x = torch.arange(1,21).reshape(2,2,5)
x

tensor([[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]]])

In [142]:
x_stack = torch.stack([x,x],dim=3)
x_stack

tensor([[[[ 1,  1],
          [ 2,  2],
          [ 3,  3],
          [ 4,  4],
          [ 5,  5]],

         [[ 6,  6],
          [ 7,  7],
          [ 8,  8],
          [ 9,  9],
          [10, 10]]],


        [[[11, 11],
          [12, 12],
          [13, 13],
          [14, 14],
          [15, 15]],

         [[16, 16],
          [17, 17],
          [18, 18],
          [19, 19],
          [20, 20]]]])

In [143]:
x_stack = torch.stack([x,x],dim=2)
x_stack

tensor([[[[ 1,  2,  3,  4,  5],
          [ 1,  2,  3,  4,  5]],

         [[ 6,  7,  8,  9, 10],
          [ 6,  7,  8,  9, 10]]],


        [[[11, 12, 13, 14, 15],
          [11, 12, 13, 14, 15]],

         [[16, 17, 18, 19, 20],
          [16, 17, 18, 19, 20]]]])

In [144]:
x_stack = torch.stack([x,x],dim=1)
x_stack

tensor([[[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]]],


        [[[11, 12, 13, 14, 15],
          [16, 17, 18, 19, 20]],

         [[11, 12, 13, 14, 15],
          [16, 17, 18, 19, 20]]]])

In [145]:
x_stack = torch.stack([x,x],dim=0)
x_stack

tensor([[[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[11, 12, 13, 14, 15],
          [16, 17, 18, 19, 20]]],


        [[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[11, 12, 13, 14, 15],
          [16, 17, 18, 19, 20]]]])

In [147]:
x_stack = torch.vstack([x,x])
x_stack

tensor([[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]]])

In [148]:
x_stack = torch.hstack([x,x])
x_stack

tensor([[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20],
         [11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]]])

### Squeezing and Unsqueezing Tensors

In [154]:
torch.squeeze(x.reshape(1,2,10)).shape, x.reshape(1,2,10)

(torch.Size([2, 10]),
 tensor([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
          [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]]]))

In [164]:
x.unsqueeze(dim=0).shape,x.unsqueeze(dim=0)

(torch.Size([1, 2, 2, 5]),
 tensor([[[[ 1,  2,  3,  4,  5],
           [ 6,  7,  8,  9, 10]],
 
          [[11, 12, 13, 14, 15],
           [16, 17, 18, 19, 20]]]]))

In [165]:
x.unsqueeze(dim=1).shape,x.unsqueeze(dim=1)

(torch.Size([2, 1, 2, 5]),
 tensor([[[[ 1,  2,  3,  4,  5],
           [ 6,  7,  8,  9, 10]]],
 
 
         [[[11, 12, 13, 14, 15],
           [16, 17, 18, 19, 20]]]]))

In [166]:
x.unsqueeze(dim=2).shape,x.unsqueeze(dim=2)

(torch.Size([2, 2, 1, 5]),
 tensor([[[[ 1,  2,  3,  4,  5]],
 
          [[ 6,  7,  8,  9, 10]]],
 
 
         [[[11, 12, 13, 14, 15]],
 
          [[16, 17, 18, 19, 20]]]]))

In [167]:
x.unsqueeze(dim=3).shape,x.unsqueeze(dim=3)

(torch.Size([2, 2, 5, 1]),
 tensor([[[[ 1],
           [ 2],
           [ 3],
           [ 4],
           [ 5]],
 
          [[ 6],
           [ 7],
           [ 8],
           [ 9],
           [10]]],
 
 
         [[[11],
           [12],
           [13],
           [14],
           [15]],
 
          [[16],
           [17],
           [18],
           [19],
           [20]]]]))

### ```torch.permute()```

Returns the view by permutating the original tensor (swap the order of the originial tensor)


In [173]:
x = torch.rand(size=(224,224,3))
x

tensor([[[0.1976, 0.8452, 0.9250],
         [0.7465, 0.4456, 0.9446],
         [0.6438, 0.1466, 0.1197],
         ...,
         [0.8020, 0.7068, 0.3059],
         [0.5934, 0.3813, 0.1209],
         [0.6386, 0.2834, 0.0152]],

        [[0.7965, 0.3749, 0.9959],
         [0.1768, 0.0247, 0.1048],
         [0.8032, 0.2988, 0.2477],
         ...,
         [0.1620, 0.4115, 0.9894],
         [0.0446, 0.6745, 0.5366],
         [0.5788, 0.3234, 0.5783]],

        [[0.2984, 0.2503, 0.2172],
         [0.0647, 0.3215, 0.9556],
         [0.8112, 0.3283, 0.0493],
         ...,
         [0.5740, 0.1233, 0.3923],
         [0.3495, 0.7212, 0.9125],
         [0.8877, 0.7825, 0.6082]],

        ...,

        [[0.7285, 0.4801, 0.1878],
         [0.3109, 0.0073, 0.1715],
         [0.1558, 0.1007, 0.2127],
         ...,
         [0.6730, 0.0528, 0.2958],
         [0.9215, 0.6401, 0.9898],
         [0.9755, 0.2918, 0.5791]],

        [[0.4395, 0.1865, 0.5108],
         [0.1519, 0.0348, 0.0957],
         [0.

In [192]:
x_permuted = torch.permute(x,(1,2,0))
x_permuted.shape

torch.Size([224, 3, 224])

## Selecting data from tensors INDEXING!

In [215]:
# Selecting data from tensors is similar to numpy indexing

x = torch.arange(1,28).reshape(3,3,3)
x

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24],
         [25, 26, 27]]])

In [217]:
x[1][0]

tensor([10, 11, 12])

In [221]:
x[:,1,1]

tensor([ 5, 14, 23])

In [223]:
 x[0,0,:]

tensor([1, 2, 3])